[project]
name = "try-out-selenium"
version = "0.1.0"
description = "Tryin' out selenium"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest>=8.3.5",
    "selenium>=4.31.0",
]
