name: xyz
description: "contains MAD lab exercises"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Bricolage Grotesque 
      fonts:
        - asset: static/fonts/BricolageGrotesque.ttf
    - family: DM Sans
      fonts:
        - asset: static/fonts/DMSans.ttf