name: xyz
description: "contains MAD lab exercises"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.1
  url_launcher: ^6.3.1
  fl_chart: ^0.70.2
  crypto: ^3.0.6
  bcrypt: ^1.1.3
  path_provider: ^2.1.5
  path: ^1.9.0
  sqflite: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Bricolage Grotesque 
      fonts:
        - asset: static/fonts/BricolageGrotesque.ttf
    - family: DM Sans
      fonts:
        - asset: static/fonts/DMSans.ttf